version: "3.7"

services:
  wp:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      WORDPRESS_DB_USER: $WORDPRESS_DB_USER
      WORDPRESS_DB_PASSWORD: $WORDPRESS_DB_PASSWORD
      WORDPRESS_DB_NAME: sarasa
      WORDPRESS_DB_HOST: 172.31.3.8
      WORDPRESS_DB_CHARSET: utf8mb4
      WORDPRESS_DEBUG: 0
      WORDPRESS_CONFIG_EXTRA: |
        'access-key-id' => '$BUCKET_ACCESS_KEY_ID',
        'secret-access-key' => '$BUCKET_SECRET_ACCESS_KEY',)));
    restart: unless-stopped
