on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Vault Warden secrets replacement
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: secrets replacement
        uses: actions/vaultwareden-replace-secrets-action@v1.1.0
        id: secret_replace
        with:
          BW_CLIENTID: ${{ secrets.BW_CLIENTID }}
          BW_CLIENTSECRET: ${{ secrets.BW_CLIENTSECRET }}
          BW_PASSWORD: ${{ secrets.BW_PASSWORD }}
          BW_SERVER: ${{ vars.BW_SERVER }}
          FILE_TO_REPLACE: deploy/docker-compose.yaml
      
      - name: Get the output time
        run: cat deploy/docker-compose.yaml.replaced
