on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Vault Warden secrets replacement
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: secrets replacement
        uses: matiuhart/vaultwarden-replace-secrets-action@dev
        with:
          BW_CLIENTID: ${{ secrets.BW_CLIENTID }}
          BW_CLIENTSECRET: ${{ secrets.BW_CLIENTSECRET }}
          BW_PASSWORD: ${{ secrets.BW_PASSWORD }}
          BW_SERVER: ${{ vars.BW_SERVER }}
          FILES_TO_REPLACE: |- 
            example_template_files/docker-compose1.yaml
     
      - name: Get the output for docker-compose1 file
        run: cat example_template_files/docker-compose1.yaml.replaced

      # - name: Get the output for docker-compose2 file
      #   run: cat example_template_files/docker-compose2.yaml.replaced